[package]
name = "rust-upload-file-benchmark"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
anyhow = { version = "1.0.97", features = ["backtrace"] }
axum = "0.8.1"
bytes = "1.10.1"
clap = { version = "4.5.32", features = ["derive"] }
futures = "0.3.31"
reqwest = { version = "0.12.15", features = ["stream"] }
tokio = { version = "1.44.1", features = ["full"] }
tokio-uring = { version = "0.5.0", features = ["bytes"] }
tokio-util = { version = "0.7.14", features = ["io"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "time"] }
