name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'feat/**'
  schedule:
    - cron: '0 0 * * 0' # at midnight of each sunday
  workflow_dispatch:

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: just ci
